//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sniper.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class SysPermission
    {
        public System.Guid Id { get; set; }
        public string SysResource { get; set; }
        public System.Guid RoleId { get; set; }
        public System.Guid Creator { get; set; }
        public System.DateTime CreationTime { get; set; }
    
        public virtual SysRole SysRole { get; set; }
        public virtual SysUser SysUser { get; set; }
    }
}
