//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sniper.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class SysStore
    {
        public System.Guid Id { get; set; }
        public string Name { get; set; }
        public bool SslEnabled { get; set; }
        public bool Disabled { get; set; }
        public string IconClass { get; set; }
        public string CompanyName { get; set; }
        public System.Guid Creator { get; set; }
        public System.DateTime CreationTime { get; set; }
        public Nullable<System.Guid> Modifier { get; set; }
        public Nullable<System.DateTime> ModifiedTime { get; set; }
    
        public virtual SysUser SysUser { get; set; }
        public virtual SysUser SysUser1 { get; set; }
    }
}
