//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sniper.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class SysUser
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SysUser()
        {
            this.SysPermission = new HashSet<SysPermission>();
            this.SysRole = new HashSet<SysRole>();
            this.SysRole1 = new HashSet<SysRole>();
            this.SysStore = new HashSet<SysStore>();
            this.SysStore1 = new HashSet<SysStore>();
            this.SysUser11 = new HashSet<SysUser>();
            this.SysUserLoginLog = new HashSet<SysUserLoginLog>();
            this.SysUserRole = new HashSet<SysUserRole>();
            this.SysUserToken = new HashSet<SysUserToken>();
        }
    
        public System.Guid Id { get; set; }
        public string Account { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public string MobilePhone { get; set; }
        public string Password { get; set; }
        public string Salt { get; set; }
        public string Sex { get; set; }
        public bool Enabled { get; set; }
        public bool IsAdmin { get; set; }
        public System.DateTime CreationTime { get; set; }
        public int LoginFailedNum { get; set; }
        public Nullable<System.DateTime> AllowLoginTime { get; set; }
        public bool LoginLock { get; set; }
        public Nullable<System.DateTime> LastLoginTime { get; set; }
        public string LastIpAddress { get; set; }
        public Nullable<System.DateTime> LastActivityTime { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<System.DateTime> DeletedTime { get; set; }
        public Nullable<System.DateTime> ModifiedTime { get; set; }
        public Nullable<System.Guid> Modifier { get; set; }
        public Nullable<System.Guid> Creator { get; set; }
        public byte[] Avatar { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SysPermission> SysPermission { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SysRole> SysRole { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SysRole> SysRole1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SysStore> SysStore { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SysStore> SysStore1 { get; set; }
        public virtual SysUser SysUser1 { get; set; }
        public virtual SysUser SysUser2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SysUser> SysUser11 { get; set; }
        public virtual SysUser SysUser3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SysUserLoginLog> SysUserLoginLog { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SysUserRole> SysUserRole { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SysUserToken> SysUserToken { get; set; }
    }
}
